In [1]:
import pandas as pd
import json
import geopandas as gpd

In [2]:
county = gpd.read_file('county.json')

In [17]:
county.head()

,STATEFP,COUNTYFP,COUNTYNS,AFFGEOID,GEOID,NAME,LSAD,ALAND,AWATER,geometry
0,39,131,01074078,0500000US39131,39131,Pike,06,1140324458,9567612,"POLYGON ((-83.35353099999999 39.197585, -82.78..."
1,46,3,01266983,0500000US46003,46003,Aurora,06,1834813753,11201379,"POLYGON ((-98.807771 43.935223, -98.331508 43...."
2,55,35,01581077,0500000US55035,55035,Eau Claire,06,1652211310,18848512,"POLYGON ((-91.65045499999999 44.855951, -90.92..."
3,72,145,01804553,0500000US72145,72145,Vega Baja,13,118766803,57805868,"POLYGON ((-66.43895000739889 18.4814929092627,..."
4,48,259,01383915,0500000US48259,48259,Kendall,06,1715747531,1496797,"POLYGON ((-98.920147 30.13829, -98.587897 30.1..."

In [7]:
maindata = pd.read_csv('data/maindata.csv')

In [13]:
maindata.head()

,STATEFIP,COUNTYFIPS,totalpop,targage1wtd,targage2wtd,malewtd,femalewtd,targ1wtd,targ2wtd,coveredwtd,...,likelytarg1wtd,targage1pp,targage2pp,malepp,femalepp,targ1pp,targ2pp,coveredpp,insurlikelypp,likelytarg1pp
0,48.0,61.0,844270.0,54031.0,36620.0,202357.0,216420.0,26756.0,18138.0,291238.0,...,0.0,0.137047,-0.067631,-0.089422,-0.074036,0.145625,-0.062370,-0.205880,0.037759,0.0
1,48.0,479.0,542386.0,34182.0,25442.0,129365.0,136531.0,16701.0,12646.0,184188.0,...,0.0,-0.150664,-0.241323,-0.289228,-0.285328,-0.151771,-0.236123,-0.374794,-0.224426,0.0
2,49.0,49.0,1184598.0,74294.0,80437.0,283820.0,279925.0,35450.0,40478.0,506207.0,...,0.0,0.430760,0.613226,0.133573,0.093923,0.402767,0.644413,0.133321,-0.218505,0.0
3,48.0,215.0,1699686.0,106464.0,77058.0,403741.0,424614.0,52384.0,38561.0,552800.0,...,0.0,0.897065,0.560721,0.461841,0.476598,0.903623,0.583764,0.206840,0.615054,0.0
4,6.0,107.0,920874.0,54526.0,41176.0,228106.0,228139.0,26735.0,19910.0,385518.0,...,0.0,0.144222,0.003163,-0.018937,-0.043042,0.145004,-0.006308,-0.057115,0.262898,0.0

In [11]:
maindata.STATEFIP = pd.Series(maindata.STATEFIP, dtype = 'int32')
maindata.COUNTYFIPS = pd.Series(maindata.COUNTYFIPS, dtype = 'int32')

In [20]:
county.STATEFP = pd.Series(county.STATEFP, dtype = 'float64')
county.COUNTYFP = pd.Series(county.COUNTYFP, dtype = 'float64')

In [21]:
county.dtypes

STATEFP     float64
COUNTYFP    float64
COUNTYNS     object
AFFGEOID     object
GEOID        object
NAME         object
LSAD         object
ALAND         int64
AWATER        int64
geometry     object
dtype: object

In [22]:
newdata = pd.merge(county, maindata, how = 'left', left_on = ['STATEFP', 'COUNTYFP'], right_on=['STATEFIP','COUNTYFIPS'])

In [28]:
newdata.dtypes

STATEFP           float64
COUNTYFP          float64
COUNTYNS           object
AFFGEOID           object
GEOID              object
NAME               object
LSAD               object
ALAND               int64
AWATER              int64
geometry           object
STATEFIP          float64
COUNTYFIPS        float64
totalpop          float64
targage1wtd       float64
targage2wtd       float64
malewtd           float64
femalewtd         float64
targ1wtd          float64
targ2wtd          float64
coveredwtd        float64
insurlikelywtd    float64
likelytarg1wtd    float64
targage1pp        float64
targage2pp        float64
malepp            float64
femalepp          float64
targ1pp           float64
targ2pp           float64
coveredpp         float64
insurlikelypp     float64
likelytarg1pp     float64
dtype: object

In [30]:
newdata.to_file('countymerged.json', driver = 'GeoJSON')