In [41]:
import pandas as pd
import json
import geopandas as gpd

In [42]:
county = gpd.read_file('county.json')

In [43]:
county.head()

,STATEFP,COUNTYFP,COUNTYNS,AFFGEOID,GEOID,NAME,LSAD,ALAND,AWATER,geometry
0,19,107,00465242,0500000US19107,19107,Keokuk,06,1500067253,1929323,"POLYGON ((-92.41199499999999 41.509548, -92.35..."
1,19,189,00465283,0500000US19189,19189,Winnebago,06,1037261946,3182052,"POLYGON ((-93.6485330413135 43.4995586947376, ..."
2,20,093,00485011,0500000US20093,20093,Kearny,06,2254696689,1133601,"POLYGON ((-101.542312 38.263207, -101.442485 3..."
3,20,123,00485026,0500000US20123,20123,Mitchell,06,1817632928,44979981,"POLYGON ((-98.48738399999999 39.567492, -98.48..."
4,20,187,00485055,0500000US20187,20187,Stanton,06,1762104518,178555,"POLYGON ((-102.041585 37.644282, -102.041582 3..."

In [44]:
maindata = pd.read_csv('normalized.csv')

In [45]:
maindata.head()

,STATE,STATENAME,COUNTY,TOTAL,NUMM1112,NUMF1112,NUMM1826,NUMF1826,PPM1112,PPF1112,PPM1826,PPF1826
0,1,ALABAMA,1,988772,0.006446,0.006652,0.004154,0.004311,0.557891,0.654264,0.135064,0.229200
1,1,ALABAMA,3,3463860,0.019103,0.019378,0.013433,0.013772,0.471920,0.544019,0.118012,0.197743
2,1,ALABAMA,5,485312,0.002478,0.002468,0.002844,0.001921,0.436907,0.494580,0.222246,0.196707
3,1,ALABAMA,7,408584,0.002271,0.002028,0.002272,0.001716,0.475660,0.482690,0.206550,0.216443
4,1,ALABAMA,9,1036496,0.006159,0.006221,0.004240,0.004297,0.508489,0.583629,0.129253,0.211747

In [46]:
county.STATEFP = pd.Series(county.STATEFP, dtype = 'float64')
county.COUNTYFP = pd.Series(county.COUNTYFP, dtype = 'float64')

In [47]:
newdata = pd.merge(county, maindata, how = 'left', left_on = ['STATEFP', 'COUNTYFP'], right_on=['STATE','COUNTY'])

In [48]:
newdata.to_file('countymerged.json', driver = 'GeoJSON')